baseurl = "https://hugosomb.github.io/"
title = "hugo somboonsin"
theme = "hugo-theme-console"
languageCode = "en-gb"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"

  [[params.navlinks]]
  name = "links/"
  url = "links/"
  
  [[params.navlinks]]
  name = "photos/"
  url = "photos/"